version: '3.7'

services:
  cat-app:
    image: mikesir87/cats
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.frontend.rule=Host:cats.localhost"
        - "traefik.port=5000"
        - "traefik.network=traefik"
networks:
  traefik:
   external: true